console-log-level=notice
show-console-readout=false
summary-interval=0

input-file=${HOME}/Downloads/.aria2.session
save-session=${HOME}/Downloads/.aria2.session
save-session-interval=15
auto-save-interval=15

enable-rpc=true
# rpc-secret=
rpc-listen-port=6800
rpc-listen-all=false
rpc-allow-origin-all=true

dir=${HOME}/Downloads/
continue=true
remote-time=true
always-resume=false
follow-torrent=false

disable-ipv6=false
http-accept-gzip=true
min-tls-version=TLSv1.2
content-disposition-default-utf8=true

timeout=60
connect-timeout=60

max-tries=5
retry-wait=15
max-file-not-found=1

split=32
piece-length=4M
min-split-size=16M
max-concurrent-downloads=8
max-connection-per-server=16
allow-piece-length-change=true

disk-cache=256M
file-allocation=falloc

user-agent='Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36'
